### ISSUE TITLE
Support to save scratches between sessions

### ISSUE THREAD

**Issue by semente** [ieure/scratch-el#2]
Automatically saving scratches in disk and restoring they during the init would be great. It could save in ~/.emacs.d/scratch/<mode>.

**Comment by ieure** [comment]
This isn't something I'm interested in implementing, since these are intended to be transient.

**Comment by hakantunc** [comment]
You can use the [persistent-scratch](https://github.com/Fanael/persistent-scratch) package to save buffers across sessions. Below is an example to enable persistency for an **org-mode** buffer.

```emacs-lisp
(setq persistent-scratch-scratch-buffer-p-function
        (lambda ()
          (-contains? '("*scratch*" "*org*") (buffer-name))))
```
